### ISSUE TITLE
Citations in ipython notebooks does not work in figure captions

### ISSUE THREAD

**Issue by simetenn** [doconce/doconce#102]
Hi!

It seems that citations in ipython notebooks does not work when they are inside figure captions.

A minimal working example:

```
===== Figure =====

See figure ref{PythonDict} for an illustration that explains the python dictionary concept.

FIGURE: [PythonDict.jpg] Data structure concept of a dictionary in python. From cite{PythonDict}. label{PythonDict}

Let us cite the image here as well: from cite{PythonDict}.

===== References =====

BIBFILE: papers.pub
```

And compiling it with `doconce format ipynb reference1.do.txt` we get the following notebook:

![Screenshot from 2021-02-16 20-06-37](https://user-images.githubusercontent.com/4680339/108251128-565d9880-7157-11eb-99ea-b4a1814d48c0.png)

Which has the wrong referencing in the image caption. If this is already a known issue, just disregard this issue. Thanks for your time!

Attachments:
pub file(renamed to .txt as github does not support .pub extension): [papers.txt](https://github.com/doconce/doconce/files/5997927/papers.txt)
Image: ![PythonDict](https://user-images.githubusercontent.com/4680339/108253352-f87e8000-7159-11eb-881f-67e6cde24796.jpg)

**Comment by aless80** [comment]
Thank you for the issue. 

I think there is a workaround: place the `label` before or below the figure (but leave an empty line below the figure's caption). 

On the other hand the reference on the citation won't show the number `[1]` as in html, but the key of the reference (in your example it is called as the figure, i.e. `PythonDict`).

**Comment by aless80** [comment]
The `label{}` in the example is formatted as a `<div>` tag and placed on top of the figure, i.e. above it. For some reason Jupyter needs a newline to make the citation in the caption below the figure work. One can reproduce the issue in jupyter notebook with these two Jupyter cells (I called the reference `Ref`):

The citation in the caption is ok:
```
<div id="PythonDict"></div>

<img src="PythonDict.jpg" ><p style="font-size: 0.9em"><i>Figure 1: From [[Ref]](#Ref). label:</i></p>
```

The citation in the caption is badly formatted:
```
<div id="PythonDict"></div>
<img src="PythonDict.jpg" ><p style="font-size: 0.9em"><i>Figure 1: From [[Ref]](#Ref). label:</i></p>
```

**Comment by lexnederbragt** [comment]
Thanks, @aless80, this works fine now!
