### ISSUE TITLE
Add syntax check for code block syntax

### ISSUE THREAD

**Issue by lexnederbragt** [doconce/doconce#136]
EDIT by @aless80 : The original title was: "Runtime error in pdf and html for pycod -t block"

Converting https://github.com/lexnederbragt/doconce_demo/blob/master/reference1/reference1.do.txt to pdf using

```
doconce format pdflatex reference1.do.txt --latex_code_style=vrb --execute
pdflatex reference1
```

gives this in `pdf` output

<img width="682" alt="image" src="https://user-images.githubusercontent.com/1122351/114181954-69fcd280-9942-11eb-9070-58356c4d77d7.png">

Running `doconce format html reference1.do.txt --execute` gives

<img width="658" alt="image" src="https://user-images.githubusercontent.com/1122351/114182559-0c1cba80-9943-11eb-9c53-d8e8b1b8df7c.png">

The relevant python code in `reference1.do.txt` is in a `pycod -t` block. If the code were to be executed (which it shouldn't), it should indeed give a `NameError` as the variable `total` is undefined.

The same commands on https://github.com/lexnederbragt/doconce_demo/blob/master/text1/text1.do.txt do not have this problem, probably because the variable `total` is defined earlier.

Expected behaviour: no error messages following `pycod -t` blocks in `pdf` or `html` output.

**Comment by aless80** [comment]
I think it gets solved by using `pycod-t` without any space

**Comment by lexnederbragt** [comment]
Aaargh.... You are right. So, besides me being stupid, should `pycod -t` (with space) trigger an error in DocOnce?

**Comment by aless80** [comment]
No problem. Or maybe I could correct it automatically. Or leave it as is

**Comment by lexnederbragt** [comment]
I would have it throw an error and not automatically correct it (the idea being that the author may have intended something else). If you leave it like it is maybe add a warning for it to the doconce output?

**Comment by aless80** [comment]
The syntax check aborts if the code block syntax is wrong. I defined the syntax as `!bc LANG[cod|pro][postfix]` (the language LANG is not optional because it can be `cod` or `pro`). The docs could be better IMO. A table would help

**Comment by aless80** [comment]
I rewrote a couple of parts of the manual as mentioned in the previous comment. I added a few tables to give an overview of the possible options.

**Comment by lexnederbragt** [comment]
Thanks! Closing this one now.
