### ISSUE TITLE
Push signed tags 

### ISSUE THREAD

**Issue by aless80** [doconce/doconce#139]
Push signed tags so that they become visible in GitHub's [tags](https://github.com/doconce/doconce/tags) page. The aim is to be able to clone the repository using tags.

I have been pushing annotated tags as follows, but they do not show up there, e.g.:
```
git tag -a 1.5.8 94b6c4d4 -m 'signed tag for version 1.5.8'
git push origin 1.5.8
``` 
Unfortunately I cannot create signed tags yet:
```
gpg --gen-key #generate GPG key
gpg --list-secret-keys --keyid-format LONG
    pub ../<some key>  ..
    uid ..
    ssb ..
git config --global user.signingkey <some key>
git tag -s 1.5.9 -m 'signed tag for version 1.5.9'
    error: gpg failed to sign the data
    error: unable to sign the tag
```

**Comment by lexnederbragt** [comment]
Does running `git push --tags` help?

**Comment by aless80** [comment]
no

**Comment by aless80** [comment]
The previous commit did not work (I cannot see a new tag or release). 

I did the following:
* Used `gpg2` instead of `gpg` because according to users on [StackOverflow](https://stackoverflow.com/questions/39494631/gpg-failed-to-sign-the-data-fatal-failed-to-write-commit-object-git-2-10-0) it is better
  * `sudo apt install gnupg2`
  * `export GPG_TTY=$(tty)`
  * `git config --global gpg.program gpg2`
  * `git config --global commit.gpgsign true`
* This test seems to work (also for gpg2):
  * `echo "test" | gpg --clearsign`
* I pushed a commit as follows: `git commit -S -m 'version 1.5.9 and testing signing commit with -S'`
* This shows that the pushed commit was signed: `git log --show-signature -1`
* I tried to create a 1.5.9 tag and push it, but it still does not work

The following is supposed to verify a signed tag [authenticating-to-github/signing-tags](https://docs.github.com/en/github/authenticating-to-github/signing-tags):
```
git tag -v 1.4.13
object 11474f83ed7d47d689f210cefc922e98db45e22a
type commit
tag 1.4.13
tagger Kristian Gregorius Hustad <kghustad@simula.no> 1562365911 +0200

Release version 1.4.13
error: no signature 
```

**Comment by aless80** [comment]
Update: All tags I pushed in the past are present in GitHub's Release/Tag page **of my fork**.
I followed [this guide](https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository) and i was able to create a new release/tag on the latest commit.

**Comment by aless80** [comment]
This commands pushes the tags in my fork to the upstream
`git push --tags upstream`
