### ISSUE TITLE
Start subexercises in a new cell in ipynb output

### ISSUE THREAD

**Issue by lexnederbragt** [doconce/doconce#145]
This is a feature request for exercises compiled to jupyter notebooks (`ipynb` format).

When I compile exercises to notebooks for my students, I make two versions, one with the exercise only (using `--without_solutions --without_answers`). Later I'll make one with the exercises *including* the solutions/answers, and give that to the students.

The first version, exercises only, is meant for the students to work in, they will add their solutions directly into the notebook. For this, they need to add new code or markdown cells below the exercise text.

Currently, consecutive subexercises in the `--without_solutions --without_answers` version may end up in one markdown cell, which prevents adding a new cell in between. Interestingly, if either the solution (`!bsol - !esol`) or answer (`!bans - !eans`) block has a `!bc - !ec` block, the next subexercise is put in a new codecell (despite `--without_solutions --without_answers` being used).

Minimal demo: https://github.com/lexnederbragt/doconce_demo/blob/main/pub/exercise1.ipynb and https://github.com/lexnederbragt/doconce_demo/blob/main/pub/exercise1-solutions.ipynb, both generated from https://github.com/lexnederbragt/doconce_demo/blob/main/src/exercise1.do.txt via https://github.com/lexnederbragt/doconce_demo/blob/main/src/exercise1.commands.sh (note the new file structure of the demo repo). In `exercise1.ipynb`, 2c should be in its own markdown cell, and not in the same cell as 2b.

I hope this does not require complete rewrites...

**Comment by aless80** [comment]
Minimal example to reproduce this request:

`doconce format ipynb issue145.do.txt --without_solutions --without_answers`
```
===== Exercise: my second exercise =====

!bsubex
Question without code answer:
!bans
Not really.
!eans
!esubex

!bsubex
Another question without code answer.
!bans
Nothing to answer...
!eans
!esubex
```
The two questions (introduced by `!bsubex`) should have their own cell.

Note that a `!split` would not do, as it breaks a subexercise and cause doconce to throw an error and abort. Maybe this should be added to the docs.

**Comment by aless80** [comment]
Hopefully there rest is still ok, for instance behavior of code blocks with "postfixes": pycodhid, pycod-h etc.

**Comment by lexnederbragt** [comment]
Thanks, @aless80, #147 seems to be exactly what I want!
