### ISSUE TITLE
table formatting in ipynb

### ISSUE THREAD

**Issue by lexnederbragt** [doconce/doconce#149]
A recent change leads to tables being made as wide as the page in `ipynb` output.

Example from https://github.com/lexnederbragt/doconce_demo/blob/main/pub/text1.ipynb:

Currently, the table in this notebook looks like this:

![image](https://user-images.githubusercontent.com/1122351/116237970-1e7b5e80-a761-11eb-8930-75be07300480.png)

Before, it looked like this:

![image](https://user-images.githubusercontent.com/1122351/116237909-10c5d900-a761-11eb-92cf-5cc2d6f8a6cf.png)

The change seems to be caused by this line in the notebook, which currently is this:

```
<table class="table" border="1">
```

Before, it was this:

```
<table border="1">
```

Can the previous version be restored, at least for

**Comment by aless80** [comment]
Unfortunately I do not have a programmatic way to check this sort of regression issues.   
ipynb, html, and slides should look good now.

**Comment by lexnederbragt** [comment]
I have no problem finding regression issues for you (in non-programmatic ways) :-) 

Thanks for the fix! I confirm things are OK again.
