### ISSUE TITLE
Changes escape special characters in Python 3.7+ cause regular expressions to fail 

### ISSUE THREAD

**Issue by aless80** [doconce/doconce#153]
Python 3.7 introduced some changes with the `re` module for regex and some DocOnce commands fail. 

> [re.sub](https://docs.python.org/3/library/re.html#re.sub): Changed in version 3.7: Unknown escapes in repl consisting of '\' and an ASCII letter now are errors. 

For example, an error is thrown when a regular expression is applied to the references in `test/papers.pub` because the text contains: `url:          \url{http://some.where.org}`
```
python -V
    Python 3.8.0
cd test
publish import refs1.bib
publish import refs2.bib
publish import refs3.bib
doconce format sphinx testdoc --examples_as_exercises
   ...
   regex._regex_core.error: incomplete escape \u at position 874 (line 26, column 8)
```

This implies for example that `'\u'` should either be replaced by `'\\u'`, or the `re` module should be replaced by `regex` with `import regex as re`.

Even when using `regex` I am still seeing some problems with `'{'` followed by ascii letters

```
python -V
    Python 3.8.0
cd test
doconce format sphinx testdoc --examples_as_exercises
   ...
   ... incomplete escape \u at position ..

# This line in the tests fails because { and } should be scaped:
doconce subst '(newtheorem{example}.*)'  '\g<1>\n\\newtheorem{theorem}{Theorem}[section]' testdoc_bigex.p.tex
# Now it works (import regex as re)
doconce subst '(newtheorem\{example\}.*)' '\g<1>\n\\newtheorem{theorem}{Theorem}[section]' testdoc_bigex.p.tex
```

**Comment by lexnederbragt** [comment]
Could you please add the regex module as a requirement to in the documentation (if you haven't done so already)? I got a missing module error when testing the very latest commit...

**Comment by aless80** [comment]
I think it is there, in `requirements.txt`:
```
regex==2021.4.4
```
Maybe check how you install doconce?

**Comment by lexnederbragt** [comment]
Thanks, I guess `regex` is covered by `pip install DocOnce` also. I use a `yml` file for conda that I had to add `regex` to - which is no problem.

**Comment by aless80** [comment]
I think the problem was that the current doconce on PyPi is not up to date and does not include regex. That will be fixed when I upload a new version
