### ISSUE TITLE
Add option for 'alt-text'

### ISSUE THREAD

**Issue by lexnederbragt** [doconce/doconce#160]
Universal design of web content requires an alternative text for images. Could a feature be added to DocOnce to allow this? Not sure how to do it but maybe

```
FIGURE: [/path/to/file.png, width=500 alt="Picture of a flower"] Caption text label{figure_label}
```

Alternative text is added to html [like this](https://www.w3schools.com/tags/att_img_alt.asp):

```
<img src="img_girl.jpg" alt="Girl in a jacket" width="500" height="600">
```

**Comment by lexnederbragt** [comment]
Thanks for #163! Looks like it works as requested.

**Comment by lexnederbragt** [comment]
Would you be able to enable `alt=` for images in `ipynb` output? I suspect it should be easy to do by adding the `alt = ""` part to the `<img >` tag.

**Comment by aless80** [comment]
I am not done with this issue. I am implementing some features (e.g. the `sidecap`, `frac` keywords) for some other outputs.

**Comment by aless80** [comment]
The syntax for figures and movies is now
`FIGURE: [filename[, options][, sidecap=BOOL][, frac=NUM]] [caption]`
`MOVIE: [filename[, height=NUM][, width=NUM]] [caption]` 
See the docs. The old syntax without commas should still work.

Not all formats implement the keywords (`sidecap`, `frac`, etc). I haven't thoroughly checked the movies

**Comment by lexnederbragt** [comment]
Thanks! Closing this issue now.
