### ISSUE TITLE
Make first header not start a new markdown cell in ipynb

### ISSUE THREAD

**Issue by lexnederbragt** [doconce/doconce#183]
This is a follow up of #152. The *first* header in a notebook should ideally *not* be starting a new cell if it is the first text in a DocOnce file. In the notebook, before this header doconce adds the `<!-- HTML file automatically generated from DocOnce source ...` comment, which could without problems be added to the first markdown cell...

**Comment by lexnederbragt** [comment]
Not sure if #184 addresses this - sorry if my explanation wasn't clear. let me illustrate.

Using https://github.com/lexnederbragt/doconce_demo, compiling `src/text1.do.txt` to ipynb. 

1) current result - showing raw markdown for the first two cells:
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/1122351/124624425-251f0400-de7d-11eb-8002-c4120babb4b1.png">


2) desired result - showing raw markdown for the first cell:
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/1122351/124624494-35cf7a00-de7d-11eb-9c20-2e15612af8f6.png">

Does that make sense?

A totally different option for ipynb would to add the message to the metadata in the json file, not exposing it to the user of the notebook. See https://nbformat.readthedocs.io/en/latest/format_description.html#metadata...

**Comment by aless80** [comment]
Please update your installation because I see that your outputs are old. The latest version returns something similar to option 2

**Comment by lexnederbragt** [comment]
You are correct, I hand't seen that `git pull` threw an error message. Closing now.
