### ISSUE TITLE
`print(type(x))` gives no output in html

### ISSUE THREAD

**Issue by lexnederbragt** [doconce/doconce#192]
This code cell:

```
!bc pycod
x = 3
print(type(x))
!ec
```
when run with `--execute`, gives `<class 'int'>` in ipynb and pdf, but no output in html, or an empty output box in html slides. Is there a fix for this?

**Comment by aless80** [comment]
That's because `<class 'int'>` gets interpreted as html code. The `<>` characters and probably others will have to be encoded.
