### ISSUE TITLE
Create an answer book in ipynb

### ISSUE THREAD

**Issue by aless80** [doconce/doconce#194]
@lexnederbragt asked to be able to create a ipynb file with only answers and/or solutions and no exercise text. This file can be given as answer book to students. 

Compiling an input file to `ipynb` creates a `<file>_exersol.do.txt` file with answers and solutions but no code. According to some code written by the original developer this seems to be a feature useful for development. This can now be removed. 

There is also a dump of the data structure for exercises `<file>.exerinfo`, which can probably be removed as well.

There is also this command, but I think it does not work
```
doconce extract_exercises <file> --filter=ipynb
```

The `--exercises_in_zip` option creates a `standalone_exercises.zip` file with exercise texts but not answers/solutions, in addition to two files useful for compiling the exercises:
```
doconce format ipynb execute.do.txt --execute --exercises_in_zip
unzip -o exercise1_exercises.zip
ls standalone_exercises
  exercise_1.do.txt
  exercise_2.do.txt
  ..
  index.do.txt
  make.py
doconce format ipynb execute.do.txt --execute --exercise_numbering=chapter --exercises_in_zip
```
I suggest including the answers and solutions files in the zip file, in addition to some code that can be used to compile the exercise book including answers and/or solutions. I think `index.do.txt` just lists the generated `tex` and `ipynb` files, so I guess it can be removed.

**Comment by lexnederbragt** [comment]
Thanks, this looks very good and useful. One issue I found was that things seem to work very well for sub exercises that only have a solution (`!bsol` - `!esol` blocks), but not with answers (`!bans`- `!eans` blocks) or when the two are mixed. Compared to the `<file>_exersol.do.txt` file, I think the only thing (?) that is missing is the subexercise letter: I see `__b) Solution.__` but `__Answer.__` which should be `__a) Answer.__` (using `exercise1.do.txt` in my demo repo).

**Comment by aless80** [comment]
Should the answers and solutions be preceded by a letter or only when there are more than one? 

Example of a sub exercise with two answers and two solutions: 
```
# doconce format ipynb <file>.do.txt --execute --exercises_in_zip
===== Exercise: my first exercise =====

Some text

!bsubex
subexercise

!bans
ans1
!eans

!bans
ans2
!eans

!bsol
sol1
!esol

!bsol
sol2
!esol

!esubex
```

**Comment by lexnederbragt** [comment]
Subexercises should not have more than one answer and/or solution... A more realistic example:

```
# doconce format ipynb <file>.do.txt --execute --exercises_in_zip
===== Exercise: my first exercise =====

Some text

!bsubex
subexercise 1

!bans
ans1
!eans


!bsol
sol1
!esol

!esubex

!bsubex
subexercise 2

!bans
ans2
!eans

!bsol
sol2
!esol

!esubex
```

Content of `solutions.do.txt` currently is

```
===== Exercise 1: my first exercise =====

__Answer.__
ans1

__a) Solution.__
sol1


__Answer.__
ans2

__b) Solution.__
sol2
```

Desired (and here I changed my mind a bit, sorry...):

```
===== Exercise 1: my first exercise =====

__a)__

_Answer._
ans1

_Solution._
sol1

__b)__

_Answer._
ans2

_Solution._
sol2

```

**Comment by aless80** [comment]
PR #227 and PR #228

**Comment by lexnederbragt** [comment]
Seems to be working as I was hoping it would. Thanks!
