### ISSUE TITLE
New feature: enable execution in a different folder

### ISSUE THREAD

**Issue by lexnederbragt** [doconce/doconce#195]
When running `--execute`, it would be nice if the execution could be run in a different folder than where the doconce file is located. That folder might for example contain the data loaded during the execution. Something like a flag called `--execute_dir=`, and the process `cd`s into that folder before execution (or temporarily copies the doconce source file there)

**Comment by aless80** [comment]
The clear downside of this request is having to add another option. Can you clarify the user case? 

Say that you are compiling a DocOnce file using `--execute` with some python code. Currently the `do.txt` file should be written to reference any data/figure, including any data loaded during execution. Why do you need to `cd` in some other folder? Do you want to have more flexibility in writing these references? Or maybe the newly loaded data needs the python compiler to be in its own directory?

**Comment by lexnederbragt** [comment]
I write doconce files to be compiled to notebooks in a `src` folder. After compilation I move the notebook to a `pub` folder. I then have to include all figures - this is done via the `ipynb-*-src.tar.gz` file - and also python files with code that is imported in the notebook, and data files. For my students, these latter two need to be in the _same folder_ as the notebook, not using a (relative or absolute) path. I tend to forget to include these datafiles and python files. The notebook does not show any errors, but when someone re-executes it they get errors.

Being able to compile in a different folder, combined with 'abort (or warn) on error'  would save me (and the students) from this, guaranteeing that the notebook can be executed again yielding the same results without error(s).

By the way, the book authors I work with use a hack with `pycod-e` followed by a `os.chdir("folder-with_data_files")` which inspired this request...

**Comment by aless80** [comment]
I am not convinced by this request. 

It sounds to me that the file structure is not right as it does not separate the input file from the files it refers to (the "assets"). What about doing something like this (similar to the file structure in Django)?
```
.
├── assets/
│   ├── code/
│   └── img/
├── src/
│   └── input.do.txt
└── pub/
    └── output.ipynb
```
Then the DocOnce input file can use a relative path and both you and your students should be able to run the ipynb, as long as you share the assets. You can also keep `src` private.

**Comment by lexnederbragt** [comment]
This is basically what I am doing. It is not about me or students running the finished `output.ipynb`. It is about *during* conversion with `--execute`, run the execution step in `pub` (which has the data files the notebook is opening and reading), for example to check whether all datafiles are in fact present (the execution would report an error if not, of fail when used with `--execute=abort`.

I cannot use an `assets` folder with beginner students, as they do not understand file paths. I want them to be able to do `open('file.txt, 'r')`, and not have to teach them  `open('../assets/file.txt, 'r')`

**Comment by aless80** [comment]
> For my students, these latter two need to be in the same folder as the notebook, not using a (relative or absolute) path

Ok, so the main reason for this request is to protect students from learning `..`. 
You also seem to have a workaround, does it work? 

> By the way, the book authors I work with use a hack with pycod-e followed by a os.chdir("folder-with_data_files")

**Comment by lexnederbragt** [comment]
Yes. Here is a working example for the workaround. I propose to close this issue as "won't fix because there is a workaround'.

Folder structure

```.
├── src/
│   └── test.do.txt
│   └── test2.do.txt
└── pub/
    └── infile.txt
```

File `test.do.txt`:
```
Read in the data

!bc pycod
fh = open("infile.txt", 'r')
lines = fh.readlines()
fh.close()
!ec

(P.S. this may be a good use case of `pycod-e`?)

Let's print it out
!bc pycod
for line in lines:
    print(line.strip())
!ec
```

Convert with
```
doconce format ipynb test.do.txt --execute --output=../pub/test.ipynb
```

Because during the conversion, `infile.txt` is not availble, doconce reports `*** Warning: found error in code block:`


File `test2.do.txt`:
```
!bc pycod-e
import os
os.chdir("../pub")
!ec

# #include "test.do.txt"
```

Convert with
```
doconce format ipynb test2.do.txt --execute --output=../pub/test2.ipynb
```

Now during the conversion, `infile.txt` _is_ availble, no errors are reported and the output notebook is fine.

**Comment by aless80** [comment]
Close because there is a workaround
