### ISSUE TITLE
Implement formatting to jupyterbooks

### ISSUE THREAD

**Issue by aless80** [doconce/doconce#30]
[Jupyterbook](https://jupyterbook.org/intro.html): "Jupyter Book is an open source project for building beautiful, publication-quality books and documents from computational material.". This project is interesting because it allows users to visualize a book composed of text (Markdown) and interactive notebooks (Jupyter Notebooks). 

This enhancement is about allowing DocOnce user to create the files necessary to compile a Jupyterbook from a DocOnce file (.do.txt). Once installed, a template Jupyterbook can be created and built with: 

```
pip install jupter-book --user
jupyter-book create mybook 
jupyter-book build mybook 
```
The main parts of the book are 

1. the book chapters, which are Markdown and Jupyter Notebook files; 
2. the `_toc.yml` file, which lists the content of the book and refers to chapter files; 
3. configuration settings and other files such as `_config.yml`. 

Doconce should output the files in 1. and 2. from a DocOnce file, so that the user can subsequently compile the book. The chapters files in point 1. can be extracted from DocOnce sections/subsections/chapters. The TOC file in 2. should list the files in 1. DocOnce should be able to extract a chapter title for each book chapter in 1. from the corresponding DocOnce section/subsection/chapter header, if present. 

Note that Jupyterbook has moved to version 0.8, which has a different file structure than previous versions.

**Comment by lexnederbragt** [comment]
Jupyterbook has been on my radar for a while. I support this issue wholeheartedly! I can be a test user if that is of interest.

**Comment by aless80** [comment]
Thank you Lex! 

Some notes about this first implementation. 
Examples:
```
# Help on terminal
doconce jupyterbook --help
  Usage: doconce jupyterbook filename [options] 
  Create files for Jupyter Book version: 0.8
  Example: doconce jupyterbook filename.do.txt --sep=section
  Try 'doconce jupyterbook --help' for more information.

  -h                                  Show this help page
  --help                              Show this help page
  --sep=...                           Specify separator for DocOnce file into jupyter-book chapters. [chapter|section|subsection]
  --dest=...                          Destination folder for the content
  --dest_toc=...                      Destination folder for the _toc.yml file
  --titles=...                        File with page titles, i.e. titles in TOC on the left side of the page.   Default is 'auto': assign titles based on the separator headers


# Execute on a DocOnce file using the sep, dest, and dest_toc options
doconce jupyterbook mybook.do.txt --sep=section \
  --dest=/home/someuser/mybook --dest_toc=/home/someuser/mybook 

#Also use the title option
doconce jupyterbook mybook.do.txt --sep=subsection \
  --dest=/home/someuser/mybook --dest_toc=/home/someuser/mybook \
  --titles=/home/someuser/mybook/file_with_titles.txt

#doconce jupyter also accept "general" options
doconce jupyterbook mybook.do.txt --sep=chapter \
  --examples_as_exercises --allow_refs_to_external_docs
```

Possible pitfalls: The points 2 and 3 listed in the [jupyterbook documentation](https://jupyterbook.org/file-types/index.html#rules-for-all-content-types), i.e. _Use only one top-level header_ and _Headers should increase linearly_. 

According to the first point _Files must have a title_ in the [jupyterbook docs](https://jupyterbook.org/file-types/index.html#rules-for-all-content-types), the jupyter-book chapters/parts (i.e. the files that compose a jupyter-book) must have a title. The title is taken from the headers in the DocOnce file, but if none is found the title will be the basename of the DocOnce file e.g. `03_mybook`. 

I added an example of this functionality to the tests. This allowed me to discovered a few problems that I had to iron out. In particular, to make this work on `test/testdoc.do.txt` I had to use the DocOnce options `--examples_as_exercises --allow_refs_to_external_docs`. The second one is needed because references (e.g. `ref{sec:theory}`) end up in different files. The good thing is that both options were suggested by the DocOnce's output when DocOnce failed. I also had to ignore separators that are within code (the !bc and !eb directories). 

To make jupyter-book work I had to do some troubleshooting, e.g. upgrading Sphinx and jupyter-client. We might have to update the software requirements accordingly.

**Comment by aless80** [comment]
Pushed #32 , which should give more flexibility when using the title option.

After a discussion with a DocOnce user, I am considering to extend the `--sep` option or create a couple of ones such as `--sep_chapter`, `--sep_section`. The aim would be to let a user automatically create jupyter-book books with chapters sub-divided in sections. Note that jupyter-book also has the concept of parts, which are collection of chapters.

**Comment by aless80** [comment]
Pushed #33 , which introduces the subdivision of jupyter-books in sections using the `--sep_section` option. 

As before, the `--sep` splits a DocOnce document in Jupyter-book chapters. The new `--sep_section` option subdivides chapters in Jupyter-book sections. 

Users can pass custom titles to the `--titles=<file>` option as before. To help writing the titles down I created the `--show_titles` option, which prints out the titles detected in headers of the DocOnce file.

Examples:

```
# Help on terminal
doconce jupyterbook --help
  Usage: doconce jupyterbook filename [options] 
  Create files for Jupyter Book version: 0.8
  Example: doconce jupyterbook filename.do.txt --sep=section
  Try 'doconce jupyterbook --help' for more information.
  
  -h                                  Show this help page
  --help                              Show this help page
  --sep=...                           Specify separator for DocOnce file into jupyter-book chapters. [chapter|section|subsection]
  --sep_section=...                   Specify separator for DocOnce file into jupyter-book sections. [chapter|section|subsection], optional
  --dest=...                          Destination folder for the content
  --dest_toc=...                      Destination folder for the _toc.yml file
  --show_titles                       Print out the titles detected based on the separator headers. This can be helpful for the file passed to the --titles option
  --titles=...                        File with page titles, i.e. titles in TOC on the left side of the page. Default is 'auto': assign titles based on the separator headers

# Show the titles detected on a DocOnce file using the --sep and --sep_sections options
doconce jupyterbook testdoc --show_titles --sep=chapter --sep_section=subsection
  #this shows a list of titles that can be used in a title file

# Execute on a DocOnce file using the sep, sep_sections options
doconce jupyterbook testdoc  --sep=chapter --sep_section=subsection dest_toc=$PWD dest_toc=$PWD/content 

# Same, use a title file and some other DocOnce options
doconce jupyterbook testdoc  --sep=chapter --sep_section=subsection dest_toc=$PWD dest_toc=$PWD/content \
  --titles=titles.txt \
  --allow_refs_to_external_docs  --examples_as_exercises
```

**Comment by aless80** [comment]
Close
