### ISSUE TITLE
Vim Syntax Support

### ISSUE THREAD

**Issue by aless80** [doconce/doconce#35]
This is a copy of [ofenerci](https://github.com/ofenerci)'s issue in the old repository [hplgit/doconce #98](https://github.com/hplgit/doconce/issues/98)

Hi,

I wonder there is a syntax file for vim. I saw that there is already one for Emacs ( http://hplgit.github.io/doconce/doc/pub/quickref/quickref.html ). If somebody uses vim to type doconce, could she post vimrc file here?

Best Regards,
Ozhan

**Comment by erietz** [comment]
I have written a vim syntax plugin for the doconce language here: https://github.com/erietz/vim-doconce. Most features are covered, but if you find that something is missing please file an issue.

**Comment by aless80** [comment]
Thank you @erietz !
I close this issue for now
