### ISSUE TITLE
Index entries with subentries no rendering properly

### ISSUE THREAD

**Issue by MartinHeroux** [doconce/doconce#44]
**The issue**
Issue with idx{}: when backticks are used in subentries but not in primary entries, the subentries get nested one level too much.

**To Reproduce**
Compile [manual.do.txt](https://github.com/doconce/doconce/files/5625201/manual.do.txt) with the following commands:

```bash
doconce format latex manual.do.txt --no_mako --latex_font=helvetica --no_ampersand_quote --cite_doconce  --no_abort 
doconce ptex2tex manual envir=ans:nt
pdflatex -shell-escape manual
pdflatex -shell-escape manual
makeindex manual
```
**Current behaviour**
**Index**
`doconce` commands
&nbsp;&nbsp;&nbsp;&nbsp; `apply_edit_comments`, 1
&nbsp;&nbsp;&nbsp;&nbsp;`cvs2table`, 1
&nbsp;&nbsp;&nbsp;&nbsp;`remove_inline_comments`, 1
mainentry, 1
&nbsp;&nbsp;&nbsp;&nbsp;mainentry
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`bug_with_backticks`, 1
&nbsp;&nbsp;&nbsp;&nbsp;working subentry, 1

**Expected behaviour**
An index that appears like (dashes should not appear; only used to allow:

**Index**
`doconce` commands
&nbsp;&nbsp;&nbsp;&nbsp; `apply_edit_comments`, 1
&nbsp;&nbsp;&nbsp;&nbsp;`cvs2table`, 1
&nbsp;&nbsp;&nbsp;&nbsp;`remove_inline_comments`, 1
mainentry, 1
&nbsp;&nbsp;&nbsp;&nbsp;`bug_with_backticks`, 1
&nbsp;&nbsp;&nbsp;&nbsp;working subentry, 1

**Comment by aless80** [comment]
Close
