### ISSUE TITLE
--execute ignores the -t in pycod-t in latex output

### ISSUE THREAD

**Issue by lexnederbragt** [doconce/doconce#74]
Test file https://github.com/lexnederbragt/doconce_demo/blob/master/exercise1/exercise1.do.txt has a `pycod-t` block, which should not be executed with --execute.

Converting to html and ipynb gives correct output (no output if the code block is added).

Converting to pdf seems to ignore the `-t` and output is added also.

**Comment by aless80** [comment]
Isn't this meant to work Iike this, at least for the pdf format? See the manual:

> All other formats than the notebook formats ignore the -t postfix.

**Comment by lexnederbragt** [comment]
Ah, I see. The fork of doconce we use for the book for the course I'm teaching has changed that to also include latex format. I hadn't seen that was a special thing for that version. Closing now.
