### ISSUE TITLE
Rendering of python code block in markdown

### ISSUE THREAD

**Issue by lexnederbragt** [doconce/doconce#76]
Currently, a `bc pycod` block gives the following when converting to markdown output:

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~{.Python}
# python code
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

There are many `~` symbols, while current practice is only three. Can the markdown output be changed to:
```
~~~{.Python}
# python code
~~~
```

Similarly, a `bc pyout` block gives this after conversion to markdown:
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# python output
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Could this also be changed to:
```
~~~
# python output
~~~
```

**Comment by aless80** [comment]
That can be easily done, the code is in `pandoc.py`. Is it correct that this should be done for all code blocks, not only `pyout` and `pycod`? Do you have any idea if there was any reason to implement conversion with all those tildes?

**Comment by lexnederbragt** [comment]
I suspect that it should be OK for all code blocks, I have only seen these with three tildes. No idea why it was implemented with 63...
