### ISSUE TITLE
Enable use of fragment identifiers for linking to section of a html page

### ISSUE THREAD

**Issue by lexnederbragt** [doconce/doconce#85]
This is a feature request.

DocOnce sets up its table of contents with links to internal sections using `#___sec1`, `#___sec2` etc. Direct links to these then become https://doconce.github.io/doconce/doc/pub/manual/manual.html#___sec1, with `<h2 id="___sec1" class="anchor">Demos and Documentation </h2>` in the html.

However, the last years another convention is to use the *header text* as identifier - in lower case and replacing whitespace with dashes. Example: in https://github.com/doconce/doconce/blob/master/README.md, the header `### How to cite` becomes an anchor so it can be linked to directly with https://github.com/doconce/doconce/blob/master/README.md#how-to-cite. The html would then have `<h3 id="how-to-cite">How to cite</h3>` (GitHub uses a more complex version of this).

An advantage of this method of internal links is that changes in the headers (adding headers in the middle or changing their order) does not change these anchors, while in DocOnce, such changes would result in new `___sec` numbers. In other words, the links using header text as anchor names are more stable.

The request is, if this is feasible, to add a flag to `DocOnce format html` that uses the header text as anchor names for internal links (regardless of whether the `do.txt` file has `TOC: on`) and in TOCs.

Requested behaviour is then, with that flag, that

https://doconce.github.io/doconce/doc/pub/manual/manual.html#___sec1

becomes

https://doconce.github.io/doconce/doc/pub/manual/manual.html#demos-and-documentation

`<h2 id="___sec1" class="anchor">Demos and Documentation </h2>`

becomes

`<h2 id="demos-and-documentation" class="anchor">Demos and Documentation </h2>`

I do not know how duplicate headers are normally treated but I suspect each next one gets a running number.

**Comment by aless80** [comment]
Do we need to keep the first type of internal links using `___sec` or can we just phase them out and avoid adding another flag? Do you have any idea if they are documented and used for other purposes?

**Comment by lexnederbragt** [comment]
I fear phasing them out would lead to a lot (?) of broken links on the internet, so I think it better to enable both options. I do not know if hpl used some established standard, a quick google search seems to indicate not.

**Comment by lexnederbragt** [comment]
In thinking a bit more about this, this is maybe part of a bigger discussion, around whether to make such major changes the default, with the previous situation enabled using a flag, or optional, using a new flag...

**Comment by aless80** [comment]
I looked into this and will try to propose a solution soon. Correct me if I am wrong but it seems to me that `___sec` is used only in TOCs so we do not need to worry about consistency: if you compile a document to html you'll get a new TOC as I describe below, if you do not those `___sec` in the html file will still work. Unless maybe one is mixing new and old html files, but that sounds like bad practice to me.

`___sec` is used in TOCs when a heading has no label. However, I can create a label from the heading's title as GitHub does (this seems to work fine `href=re.sub('\W+', '-', title.lower()).strip('-')`. Example: a heading ```### how  !.  to cite? ###``` gives `href='how-to-cite'`. When the user requires a TOC, this `href` will be used in the links in the TOC and in the anchors in the headings.

**Comment by lexnederbragt** [comment]
It looks like `___sec` is used by default in all html output for all or most headings. However, it is only used to create links when a TOC is requested (I think).

Your solutions sounds fine. It looks like commas are also skipped from labels, e.g. https://docs.carpentries.org/topic_folders/governance/bylaws.html#eligibility-rights-and-termination-for-voting-members. Non-standard characters, such as the Norwegian 'æ', 'ø' and 'å' are also problematic. These should maybe be replaced with 'ae', 'o' and 'a' (or 'ae', 'oe' and 'aa' as is sometimes done).

**Comment by lexnederbragt** [comment]
Your implementation in #86 looks good to me! Thanks!
