### ISSUE TITLE
Testing enabling pycod-t for other formats

### ISSUE THREAD

**Issue by lexnederbragt** [doconce/doconce#89]
Coming back to #74:

I've been thinking a bit more on this and I'd like to explore enabling `pycod-t` for other formats than only ipynb. I am uncertain what the logic is behind only enabling it for ipynb. If one uses `pycod-t` one wants to exclude some, but not all, code blocks from being executed with `--execute`. It seems not to make sense to me that it still should be executed in pdf or html outputs. If one does not want code execution in html/pdf one can skip `--execute`.

Would it be much work to put this functionality in a branch so I can test it out? (so , not merge it in yet)

**Comment by aless80** [comment]
I think we should first allow code execution in formats other than `latex` and `ipynb`, as I only see `--execute` being implemented in those two formats. Code execution is implemented in the `JupyterKernelClient` class in `jupyter_execution.py`.

**Comment by lexnederbragt** [comment]
Hehe, of course - I had not realised it was not yet implemented beyond `ipynb`... Should I open a separate issue for that?

**Comment by aless80** [comment]
Yes please. Consider to list the formats you would like to see implemented
