### ISSUE TITLE
Enable --execute for other formats

### ISSUE THREAD

**Issue by lexnederbragt** [doconce/doconce#90]
Currently, code executions through `--execute` is implemented for `latex` and `ipynb`. Could it be added to `html` also? Lower priority would be `pandoc`. I don't currently see a need for other formats.

**Comment by aless80** [comment]
.. making sure that features like the final `-t` in eg `!bc pycod-t` work. 

Question: I see in the code a block of type `execute_hidden`, which is the case when it ends in `-e`. Any idea what that is? I cannot find anything about that in the documentation

**Comment by lexnederbragt** [comment]
It was introduced for the book we are working on. I'll ask the authors.

**Comment by lexnederbragt** [comment]
Could @dragly comment on this question about `pycod-e`? (One of) the relevant line(s) is https://github.com/doconce/doconce/blob/master/lib/doconce/ipynb.py#L448

**Comment by lexnederbragt** [comment]
@dragly Is this related to https://github.com/doconce/doconce/issues/91?

**Comment by aless80** [comment]
I was studying the code and the `-e` thing looks like it is an option to hide a code block even when --execute is used. In fact such a block gets marked as `execute_hidden`

**Comment by lexnederbragt** [comment]
Closing as it seems to be resolved. Thanks!
