### ISSUE TITLE
pyhid code blocks not hidden and not sharing scope with other cells

### ISSUE THREAD

**Issue by aless80** [doconce/doconce#91]
According to the manual in the 'Hidden code blocks' paragraph, the `!bc *hid` environment (e.g. `!bc pyhid`) can be used to execute code (e.g. `import sys`) in a hidden cell. Subsequent cells can use the variables or imports in that cell. 

Example:

```
Code block with pyhid (executed but hidden):
!bc pyhid
import sys
test=1
!ec


Code block using pycod:
!bc pycod
print(test)
!ec

Code block using pycod:
!bc pycod
print(sys.version)
!ec
```

Issue 1: when compiling the example with `doconce format ipynb` the first `pyhid` cell does not get hidden. I am not sure if the cell should take precedence on --execute and still be hidden. 

Issue 2: when compiling the example with `doconce format ipynb --execute`, the 2nd and 3rd blocks fail because the variable and the import are not found

**Comment by aless80** [comment]
Issue #60 resulted in a number of options for executing and showing notebook cells, some of which are not documented. It is possible that the following list of options is not 100% accurate, also because I am not sure I understand the documentation [Jupyter IPython Notebooks](https://doconce.github.io/doconce/doc/pub/manual/manual.html#do2any:ipynb). 

1. `pycod` are normal cells with type `cell`. They are visible and are be executed when using `--execute`. OK;
2. `*hid` are hidden cells, but not for the `ipynb` format. With `--execute` they should still be executed, but in the current implementation they become visible. I am not sure about this: either keep HIDDEN for all formats, or keep as is;
3. `-e` is a `execute_hidden` type, i.e. hide it even when `--execute` is used. I propose to REMOVE this option;
4. `-t` do not get executed but only displayed. I'd like to know what `-t` stands for. OK
5. `*out` to write cell outputs. There is nothing to run here. An empty cell is added before this environment if there are none. OK

Notice that options 4 and 5 could be used to simulate a cell with an error.

Therefore I wonder if we can only keep options 1, 4, 5, and option 2 but always hidden. If `--execute` is used, execute options 1 and 2. Would that work?



I will phase out the deprecated version 3 of nbformat and the `--ipynb_version` option

**Comment by lexnederbragt** [comment]
1) correct

2) HPL added `pyhid` long before `--execute` was added. This could probably also have been solved with `%if format=="ipynb"`. These block should be shown in `ipynb` *and* executed in `ipynb` when `--execute` is set. It seems that doconce from the fork where `--execute` was added does execute `pyhid` blocks. 

Note that the doconce manual says

> other formats, **with the exception of certain interactive Sphinx documents**, will hide such code

As for 3), it is used in this context in the book I am working with:

In a doconce file for a chapter, there will be this block at the top:
```
!bc pycod-e
import os
this_is_a_tmp_variable_that_never_should_be_used_in_our_code_1 = os.getcwd()
os.chdir("data-inheritance")
!ec
```

and this at the bottom:
```
!bc pycod-e
os.chdir(this_is_a_tmp_variable_that_never_should_be_used_in_our_code_1)
!ec
```

So it seems to be a trick to run the execution of the notebook in a different folder, one that has the necessary datafiles, thus preventing from having to add a path to the datafile. I am not sure we can avoid it. It could be replaced by `pyhid-e`, but that is probably confusing.

4) I think it stands for 'text' ('text only representation of code')

5) correct
