### ISSUE TITLE
Code blocks get executed as Python code when formatting to latex and html

### ISSUE THREAD

**Issue by aless80** [doconce/doconce#97]
See `test/execute.do.txt`. When formatting to latex (or to html in an upcoming pull request) with `doconce format latex execute.do.txt --execute`, any code block gets executed using Python/IPython. Therefore, code such as the following:

```
Compile this document with

!bc sh-t
doconce format ipynb execute.do.txt --execute
!ec
```
results in an error:
```
Compile this document with

\bsh
doconce format ipynb execute.do.txt --execute
\esh
\bpyout
  File "<ipython-input-2-909ae4915a71>", line 1
    doconce format ipynb execute.do.txt --execute
                 ^
SyntaxError: invalid syntax
\epyout
```

**Comment by lexnederbragt** [comment]
Related to https://github.com/doconce/doconce/issues/89, where I suggested to enable `pycod-t` for other formats than `ipynb` (and by extension, other `-t` environments).
